name: ReactJS Workflow

on:
  push:
    branches: [ main ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize workflow
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          always-auth: false
          architecture: "x64"
          node-version: "16"
          check-latest: true

      - name: Install NPM dependencies
        run: yarn install

      - name: Lint code with ESLint
        run: yarn run eslint --ext .js src/

      - name: Build React application
        run: yarn build

      - name: Deploy React application
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'user'
          server: ${{ secrets.IP_ADDR }}
          port: ${{ secrets.SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: '/home/user/nginx'
          args: '-o ConnectTimeout=10'
