name: Test, build, deploy

on:
  push:
    branches: [ rewrite ]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize job
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          always-auth: false
          architecture: "x64"
          node-version: "16"
          check-latest: true

      - name: Install dependencies
        run: yarn add eslint eslint-plugin-react react-scripts

      - name: Lint code with ESLint
        run: yarn run eslint --ext .js src/

      - name: Build React application
        run: yarn build

      - name: Deploy application to remote server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'user'
          server: '144.172.71.238'
          port: '784'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: '/home/user/nginx'
          args: '-o ConnectTimeout=10'
